default_platform(:ios)

platform :ios do
  desc "Build the iOS application for Mac Catalyst x86_64"
  lane :build_catalyst_x86_64 do
    build_app(
      workspace: "ReactReunion.xcworkspace",
      scheme: "ReactReunion",
      configuration: "Release",
      sdk: "macosx",
      xcargs: "ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO"
    )
  end

  desc "Build the iOS application for Mac Catalyst arm64"
  lane :build_catalyst_arm64 do
    build_app(
      workspace: "ReactReunion.xcworkspace",
      scheme: "ReactReunion",
      configuration: "Release",
      sdk: "macosx",
      xcargs: "ARCHS=arm64 ONLY_ACTIVE_ARCH=NO"
    )
  end
end
