name: Build React Native App

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-uikit:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Watchman
      run: brew install watchman

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        npm install
        cd ios
        pod install

    - name: Cache Xcode and CocoaPods
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/com.apple.dt.Xcode
          ios/Pods
        key: ${{ runner.os }}-xcode-cocoapods-${{ hashFiles('**/*.xcodeproj/**/*.pbxproj', 'ios/Podfile.lock') }}

    - name: Lint JavaScript
      run: |
        npm run lint -- --fix

    - name: Run JavaScript Tests
      run: |
        npm test

    - name: Bundle JavaScript for macOS
      run: |
        npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios

    - name: Build Mac Catalyst app
      working-directory: ios
      run: |
        xcodebuild -workspace ReactReunion.xcworkspace -scheme ReactReunion -sdk iphoneos \
        -destination 'generic/platform=macOS,arch=${{ matrix.arch }},variant=Mac Catalyst' \
        -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Fail if previous step failed
      if: failure()
      run: exit 1

  build-uwp:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Enable Long Paths
      run: |
        $RegistryPath = "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem"
        Set-ItemProperty -Name "LongPathsEnabled" -Value 1 -Type DWord -Path $RegistryPath

    - name: Install dependencies
      run: npm install

    - name: Cache MSBuild Artifacts
      uses: actions/cache@v4
      with:
        path: |
          windows/**/bin
          windows/**/obj
        key: ${{ runner.os }}-msbuild-${{ hashFiles('windows/**/*.vcxproj', 'windows/**/*.csproj', 'windows/**/*.sln') }}   

    - name: Lint JavaScript
      run: |
        npm run lint -- --fix

    - name: Run JavaScript Tests
      run: |
        npm test

    - name: Bundle JavaScript for Windows
      run: |
        npx react-native bundle --entry-file index.js --platform windows --dev false --bundle-output windows/main.jsbundle --assets-dest windows

    - name: Install MSBuild Log Viewer
      run: choco install msbuild-structured-log-viewer

    - name: Build UWP app
      working-directory: windows
      run: |
        msbuild /t:Restore "/p:RestoreProjectStyle=PackagesConfig;RestorePackagesConfig=true" /p:Configuration=Release /p:Platform=${{ matrix.arch }} ReactReunion.sln
        msbuild /restore /p:Configuration=Release /p:Platform=${{ matrix.arch }} ReactReunion.sln
        msbuild /p:Configuration=Release /p:Platform=${{ matrix.arch }} /verbosity:detailed /t:Build ReactReunion.sln

    - name: Fail if previous step failed
      if: failure()
      run: exit 1
