name: Build React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup cache for node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Setup cache for CocoaPods
      uses: actions/cache@v2
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Clean build folder
      run: xcodebuild clean -workspace ios/ReactReunion.xcworkspace -scheme ReactReunion

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Watchman
      run: brew install watchman

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Remove node_modules (if cache is not hit)
      run: rm -rf node_modules

    - name: Install dependencies
      run: npm install

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install dependencies
      run: pod install --project-directory=ios

    - name: Setup keychain
      run: |
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
      shell: bash

    - name: Import certificate
      env:
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -T /usr/bin/codesign

    - name: Build Mac Catalyst app
      working-directory: ios
      run: xcodebuild -workspace ReactReunion.xcworkspace -scheme ReactReunion -sdk iphoneos -destination 'platform=macOS,variant=Mac Catalyst'

    - name: Fail if previous step failed
      if: failure()
      run: exit 1

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup cache for node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        Invoke-WebRequest -Uri https://community.chocolatey.org/install.ps1 -UseBasicParsing | Invoke-Expression

    - name: Ensure Visual Studio Components
      run: |
        $components = @(
            'Microsoft.Component.MSBuild',
            'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
            'Microsoft.VisualStudio.ComponentGroup.UWP.Support',
            'Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core',
            'Microsoft.VisualStudio.Component.Windows10SDK.19041',
            'Microsoft.VisualStudio.Component.Windows11SDK.22621',
            'Microsoft.VisualStudio.ComponentGroup.UWP.VC',
            'Microsoft.VisualStudio.Workload.ManagedDesktop',
            'Microsoft.VisualStudio.Workload.NativeDesktop',
            'Microsoft.VisualStudio.Workload.Universal'
        )
        $workloads = @(
            'Microsoft.VisualStudio.Workload.ManagedDesktop',
            'Microsoft.VisualStudio.Workload.NativeDesktop',
            'Microsoft.VisualStudio.Workload.Universal'
        )
        $components = $components -join ','
        $workloads = $workloads -join ','
        choco install visualstudio2022buildtools --params "'--add $components --add $workloads --includeRecommended --quiet --wait'"

    - name: Add MSBuild to PATH
      run: echo "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Enable Developer Mode
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        $RegistryKeyPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"
        if (-not (Test-Path -Path $RegistryKeyPath)) {
          New-Item -Path $RegistryKeyPath -ItemType Directory -Force
        }
        Set-ItemProperty -Path $RegistryKeyPath -Name AllowDevelopmentWithoutDevLicense -Value 1 -Type DWord

    - name: Enable Long Paths
      run: Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -Type DWord

    - name: Install Yarn
      run: choco install yarn

    - name: Install dependencies
      run: npm install

    - name: Install MSBuild Log Viewer
      run: choco install msbuild-structured-log-viewer

    - name: Install .NET SDK
      run: choco install dotnet-6.0-sdk-4xx

    - name: Install CppWinRT VSIX
      run: |
        $url = "https://cppwinrtteam.gallerycdn.vsassets.io/extensions/cppwinrtteam/cppwinrt101804264/2.0.240405.15/1712356759635/Microsoft.Windows.CppWinRT.vsix"
        $destination = "C:\Temp\Microsoft.Windows.CppWinRT.vsix"
        if (-not (Test-Path -Path "C:\Temp")) {
            New-Item -ItemType Directory -Path "C:\Temp"
        }
        Invoke-WebRequest -Uri $url -OutFile $destination
        $vsixInstallerPath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe"
        if (Test-Path $vsixInstallerPath) {
            & $vsixInstallerPath $destination
        } else {
            Write-Host "VSIXInstaller.exe not found. Please verify the path to the Visual Studio Build Tools 2022 installation."
        }

    - name: Build UWP app
      run: |
        $msbuildPath = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
        if (Test-Path $msbuildPath) {
          & $msbuildPath /p:Configuration=Release /p:Platform=${{ matrix.arch }} /t:Build windows/ReactReunion.sln
        } else {
          Write-Host "MSBuild.exe not found at $msbuildPath"
          exit 1
        }

    - name: Fail if previous step failed
      if: failure()
      run: exit 1
