name: Build React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-uikit:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup cache for node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Setup cache for CocoaPods
      uses: actions/cache@v2
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Clean build folder
      run: xcodebuild clean -workspace ios/ReactReunion.xcworkspace -scheme ReactReunion

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Watchman
      run: brew install watchman

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Remove node_modules (if cache is not hit)
      run: rm -rf node_modules

    - name: Install dependencies
      run: npm install

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install dependencies
      run: pod install --project-directory=ios

    - name: Setup keychain
      run: |
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
      shell: bash

    - name: Import certificate
      env:
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -T /usr/bin/codesign

    - name: Build Mac Catalyst app
      working-directory: ios
      run: xcodebuild -workspace ReactReunion.xcworkspace -scheme ReactReunion -sdk iphoneos -destination 'platform=macOS,variant=Mac Catalyst'

    - name: Fail if previous step failed
      if: failure()
      run: exit 1

  build-uwp:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup cache for node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        Invoke-WebRequest -Uri https://community.chocolatey.org/install.ps1 -UseBasicParsing | Invoke-Expression

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Enable Developer Mode
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        $RegistryKeyPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"
        if (-not (Test-Path -Path $RegistryKeyPath)) {
          New-Item -Path $RegistryKeyPath -ItemType Directory -Force
        }
        Set-ItemProperty -Path $RegistryKeyPath -Name AllowDevelopmentWithoutDevLicense -Value 1 -Type DWord

    - name: Enable Long Paths
      run: Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -Type DWord

    - name: Install Yarn
      run: choco install yarn

    - name: Install dependencies
      run: npm install

    - name: Install Boost
      run: choco install boost-msvc-14.3

    - name: Set Boost environment variables
      run: |
        $env:BOOST_ROOT = "C:\Program Files\boost\boost_1_84_0"
        $env:INCLUDE = "$env:BOOST_ROOT;$env:INCLUDE"
        $env:LIB = "$env:BOOST_ROOT\stage\lib;$env:LIB"

    - name: Install MSBuild Log Viewer
      run: choco install msbuild-structured-log-viewer

    - name: Install .NET SDK
      run: choco install dotnet-6.0-sdk-4xx

    - name: Build UWP app
      run: msbuild /p:Configuration=Release /p:Platform=${{ matrix.arch }} /t:Build windows/ReactReunion.sln

    - name: Fail if previous step failed
      if: failure()
      run: exit 1
