name: Build React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-uikit:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Watchman
      run: brew install watchman

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        npm install
        cd ios
        pod install

    - name: Build Mac Catalyst app
      working-directory: ios
      run: |
        xcodebuild -workspace ReactReunion.xcworkspace -scheme ReactReunion -sdk iphoneos \
        -destination 'generic/platform=macOS,arch=${{ matrix.arch }},variant=Mac Catalyst' \
        -archivePath $RUNNER_TEMP/ReactReunion.xcarchive archive -configuration Release

    - name: Export Archive
      working-directory: ios
      run: |
        xcodebuild -exportArchive -archivePath $RUNNER_TEMP/ReactReunion.xcarchive \
        -exportPath $RUNNER_TEMP/ReactReunion -exportOptionsPlist exportOptions.plist

    - name: Fail if previous step failed
      if: failure()
      run: exit 1

  build-uwp:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Enable Long Paths
      run: |
        $RegistryPath = "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem"
        Set-ItemProperty -Name "LongPathsEnabled" -Value 1 -Type DWord -Path $RegistryPath

    - name: Install dependencies
      run: npm install

    - name: Install MSBuild Log Viewer
      run: choco install msbuild-structured-log-viewer

    - name: Build UWP app
      working-directory: windows
      run: |
        msbuild /t:Restore "/p:RestoreProjectStyle=PackagesConfig;RestorePackagesConfig=true" /p:Configuration=Release /p:Platform=${{ matrix.arch }} ReactReunion.sln
        msbuild /restore /p:Configuration=Release /p:Platform=${{ matrix.arch }} ReactReunion.sln
        msbuild /p:Configuration=Release /p:Platform=${{ matrix.arch }} /t:Build ReactReunion.sln

    - name: Fail if previous step failed
      if: failure()
      run: exit 1
